channels:
- conda-forge
dependencies:
- python=3.8.9
- pip<=22.2.2
- pip:
  - mlflow
  - cffi==1.15.1
  - cloudpickle==2.1.0
  - defusedxml==0.7.1
  - ipython==8.4.0
  - torch==1.12.0
  - torchvision==0.13.0
  - tqdm==4.64.0
name: mlflow-env
