channels:
- conda-forge
dependencies:
- python=3.10.6
- pip<=22.2.1
- pip:
  - mlflow
  - cloudpickle==2.2.0
  - ipython==8.5.0
  - torch==1.12.1
  - torchvision==0.13.1
  - tqdm==4.64.1
name: mlflow-env
