artifact_uri: localhost:5000/1/6a59b5e56b994dbbbabc8fd411a6dcec/artifacts
end_time: null
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 6a59b5e56b994dbbbabc8fd411a6dcec
run_uuid: 6a59b5e56b994dbbbabc8fd411a6dcec
source_name: ''
source_type: 4
source_version: ''
start_time: 1663287514793
status: 1
tags: []
user_id: dgcnz
